version: "3.2"

services:
  qbittelebot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: qbittelegrambot
    volumes:
      - ./config.toml:/app/config.toml
    restart: unless-stopped
    network_mode: "host"
